### ISSUE TITLE
How to re-enable password storage

### ISSUE THREAD

**Issue by fowlslegs** [ioerror/torbirdy#20]
I'm using https://github.com/swick/moz-gnome-keyring-integration and I'd like to not have to constantly enter my Thunderbird password. Even though I found it before, I can't find the about:config boolean to flip for the life of me. Can you let me know what it is?

Noah

**Comment by azadi** [comment]
I am not sure... We certainly don't do anything with passwords.

(Was this a general question?)

**Comment by fowlslegs** [comment]
You know what--there actually is no problem. I could explain to you my misunderstanding, but it's a rather weird, long and complicated, and mostly boring story, so I'll save you the time.

Thanks for the response!
