### ISSUE TITLE
Thunderbird doesn't start

### ISSUE THREAD

**Issue by hasdf** [ioerror/torbirdy#21]
If I install the XPI and restart thunderbird, it doesn't start. I then need to kill the process and start it in safe-mode to disable the plugin.

I did set the port in /etc/tor/torrc to 9150 (standard was 9050) and the problem still occurs. I started tor and tried to launch chromium with 'chromium --proxy-server="socks://127.0.0.1:9150" ' which works like expected (tested with check.torproject.org).

Running Archlinux with Thunderbird 31.3.0 (tested with and without enigmail).

Does anyone else have a working installaton of torbirdy?

**Comment by azadi** [comment]
This has been reported by at least two other users, however, I have been unable to reproduce this.

Do you see anything on the console if you start Thunderbird from the terminal? Does it say "TorBirdy registered!"?

**Comment by ioerror** [comment]
Also, another question - what are the other plugins or extensions that you have loaded?

**Comment by hasdf** [comment]
Trying with a new profile in Thunderbird worked! Maybe you shoud add that to the wiki.

With the old profile:
First I tried with enigmail enabled, then no other Plugins enabled. Also deinstalling them didn't work.

0. Start Thunderbird
1. Install torbirdy.xpi
2. Close Thunderbird
3. Start Thunderbird:

[hasdf@hasdf-pc ~]$ thunderbird

(process:14009): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

# End of command line output (with that space)

Nothing else. That GLib error also shows up if I start thunderbird with no plugins.

System:
3.17.6-1-ARCH
Thunderbird 31.3.0
torbirdy xpi from mozilla plugins (also tried https://www.torproject.org/dist/torbirdy/torbirdy-current.xpi)

Thank you for your fast answer (and your great talks at 31c3 ;)
